FROM node:18-alpine

WORKDIR /app

RUN apk add --no-cache bash git curl

COPY package*.json ./
RUN npm install

COPY . .

COPY wait-for-it.sh ./wait-for-it.sh
RUN chmod +x ./wait-for-it.sh

CMD ["./wait-for-it.sh", "redis:6379", "--", "node", "repoWorker.js"]
